### ISSUE TITLE
Routes not being saved

### ISSUE THREAD

**Issue by T3ll1nG** [Tomslack/ManbabyDungeonTools#10]
The routes are not correctly saved. You can't load your old routes and if you do a new route it is only temporarily saved. A /reload wipes the addon back to default, so does closing the game.

**Comment by GrantiMC** [comment]
have the problem too

**Comment by sysasysa** [comment]
Same issue, after relogging or even reloading UI, the imported routes disappeared

**Comment by Tomslack** [comment]
This should now be resolved thanks to Toesmasher
