### ISSUE TITLE
Second floor of Necrotic Wake doesn't have a down button

### ISSUE THREAD

**Issue by cody-young** [Tomslack/ManbabyDungeonTools#104]
I happened to merge a pull from the first floor of necrotic wake with the second floor of necrotic wake, and I noticed that there's no down button on the second floor of necrotic wake. Specifically Stitchflesh's room.

**Comment by CalistusK** [comment]
I believe this is intentional so as to not mislead users into thinking you can freely move up and down, as there is no way to go back down from Stitchwerks or Zolramus apart from dying. You may still use the sublevel dropdown in the top left to quickly move between maps for Necrotic Wake.

**Comment by cody-young** [comment]
Ahh, that makes sense. Thanks for the reply!
