### ISSUE TITLE
Saving Routes seems to not work

### ISSUE THREAD

**Issue by Mirokira** [Tomslack/ManbabyDungeonTools#18]
So whenever i import a route it will import fine but as soon as i relog the route will not be there anymore.

**Comment by baruchvlz** [comment]
Dup: https://github.com/Tomslack/ManbabyDungeonTools/issues/10

**Comment by srenauld** [comment]
@baruchvlz is right - with the current version (1.1.0), I cannot replicate.

Pick up that, unzip it, and go from there!

**Comment by Tomslack** [comment]
Fixed with newest version.
