### ISSUE TITLE
Release required for support with WowUp

### ISSUE THREAD

**Issue by prateem** [Tomslack/ManbabyDungeonTools#2]
Not sure if this is something that's a priority or not but for those that use WoWUp, to install via Github there needs to be a release asset.

See:

https://i.imgur.com/8GIEhRk.png

**Comment by miasmos** [comment]
+1, also experiencing this

**Comment by jstasila** [comment]
+1, having the same problem as Mr. prateem and Mr. stephenpoole

**Comment by Defenex** [comment]
@Tomslack  I think this can be fixed by adding a zip of the source to the release artifacts. I think it should be ManbabyDungeonTools.zip that contains the folder ManbabyDungeonTools that contains all the addon files from the repo.

**Comment by Tomslack** [comment]
Thanks for that, I've added a release asset.
