### ISSUE TITLE
Not working D:

### ISSUE THREAD

**Issue by shaunpj** [Tomslack/ManbabyDungeonTools#24]
I downloaded the file, extracted it to my addons folder for retail, and its not working any help would be greatly appreciated.

**Comment by madar2252** [comment]
the folder name should be "ManbabyDungeonTools" , delete the "-main" if it's still there

**Comment by shaunpj** [comment]
BRUH you're da man!!! that fixed it tysm!

**Comment by srenauld** [comment]
Closing since resolved 👍
