### ISSUE TITLE
Addon Not Popping Up In Game

### ISSUE THREAD

**Issue by Nelwin77** [Tomslack/ManbabyDungeonTools#25]
I have downloaded and extracted this addon to the WOW folder, and its in my addon folder with all the info, but whenever I open my game the addon doesn't seem to pop up in my addon list anywhere for me to actually use in game not sure what I'm missing if you could possibly assist with a suggestion.

**Comment by srenauld** [comment]
Guessing you found how, judging by the closure :-)

I'll sort out releases so the zip file is done properly when I get around to modifying a few things.
