### ISSUE TITLE
Failed To load (Various)

### ISSUE THREAD

**Issue by FilthySerf** [Tomslack/ManbabyDungeonTools#3]
Upon loading into the game after installing the addon, I'm greeted with all of these errors. (ignore the x2 part, I had relogged to see if it stayed around so it counted each error twice)

![image](https://user-images.githubusercontent.com/68087666/103146289-58c9e600-4704-11eb-96c3-fc8780c51c57.png)

It looks like you're missing a bunch of the library files from the original MDT.

Mythic Dungeon Tools on Left, ManBaby on Right

![image](https://user-images.githubusercontent.com/68087666/103146326-ba8a5000-4704-11eb-9e7f-7a386e7e85ad.png)

Moving over the missing library files fixes most of the errors.

![image](https://user-images.githubusercontent.com/68087666/103146351-279de580-4705-11eb-854d-b4bc496c6a2f.png)

**Comment by ShaanMeisterr** [comment]
same issue
1x ...eManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua:1042: bad argument #1 to 'random' (interval is empty)
[string "=[C]"]: in function `random'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:1042: in function `UpdateBottomText'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:676: in function `ShowInterface'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:62: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5093: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4757: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4793: in function <FrameXML\ChatFrame.lua:4789>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = 0

**Comment by Nercus** [comment]
> same issue
> 1x ...eManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua:1042: bad argument #1 to 'random' (interval is empty)
> [string "=[C]"]: in function `random' [string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:1042: in function `UpdateBottomText'
> [string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:676: in function `ShowInterface' [string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:62: in function `?'
> [string "@FrameXML\ChatFrame.lua"]:5093: in function `ChatEdit_ParseText' [string "@FrameXML\ChatFrame.lua"]:4757: in function `ChatEdit_SendText'
> [string "@FrameXML\ChatFrame.lua"]:4793: in function <FrameXML\ChatFrame.lua:4789>
> [string "=[C]"]: in function `ChatEdit_OnEnterPressed'
> [string "_:OnEnterPressed"]:1: in function <[string "_:OnEnterPressed"]:1>
> 
> Locals:
> (*temporary) = 0

this is another issue and is not caused by the missing libs

**Comment by Tomslack** [comment]
Libs are now uploaded to the repository as well. 2nd issue has it's own reporting in a seperate report.

Thanks both
