### ISSUE TITLE
ManBabyDungeonTools not loading. 

### ISSUE THREAD

**Issue by Neparo** [Tomslack/ManbabyDungeonTools#30]
I attempted to download and install this version of the addon for use, however when I reloaded and relogged I could not get this version of the addon to show up in my addon list.  I would LOVE to use this version for the lols, as it stands your data input string works wonderful and I'm using it at this moment.

**Comment by srenauld** [comment]
To be specific, which version did you download? (Largely so I can test/repro)

Before releasing 1.1.2, I tested it locally, and can get it to load and show up np

**Comment by Tomslack** [comment]
I think the issue that's occuring here is that you've downloaded from github rather than downloading the release asset.

You can either download the release asset to solve this problem or you can remove the -main from the file in your addon folder and that should fix this!

**Comment by Neparo** [comment]
> I think the issue that's occuring here is that you've downloaded from github rather than downloading the release asset.
> 
> You can either download the release asset to solve this problem or you can remove the -main from the file in your addon folder and that should fix this!

I'll try that, will update

**Comment by Rubyurek** [comment]
How to install ManbabyDungeonTools:
Go to WowUp > Install Addons > URL Install > Put link > Install

That works.

**Comment by Neparo** [comment]
I deleted the "-main" and it worked, i wasn't aware i downloaded the wrong thing.  I'm a github noob.

Thanks for the assistance
