### ISSUE TITLE
Routes dont save

### ISSUE THREAD

**Issue by Gennoken** [Tomslack/ManbabyDungeonTools#35]
v1.1.2

upon dc/relog the routes i created are gone.

**Comment by srenauld** [comment]
Hey @Gennoken !

I rolled out a bunch of changes after Guilty changed the name to DungeonTools, and tried saving a route - everything seems to be in order on 1.1.6.

Can you give it a quick shot on that version (1.1.6 - you can pick it up on wowup or through the releases - https://github.com/LetsTimeIt/DungeonTools/releases/tag/v1.1.6 ), and see if you still have issues?

**Comment by Gennoken** [comment]
> Hey @Gennoken !
> 
> I rolled out a bunch of changes after Guilty changed the name to DungeonTools, and tried saving a route - everything seems to be in order on 1.1.6.
> 
> Can you give it a quick shot on that version (1.1.6 - you can pick it up on wowup or through the releases - https://github.com/LetsTimeIt/DungeonTools/releases/tag/v1.1.6 ), and see if you still have issues?

Seem to work fine.
