### ISSUE TITLE
Client don't see the addon 

### ISSUE THREAD

**Issue by Androzavrus** [Tomslack/ManbabyDungeonTools#37]
I have downloaded an addon recently and it doesn't work from the start because client doesn't see him in modifications.

**Comment by travisneids** [comment]
Can you please confirm that you are downloading the release and not the source code? https://github.com/LetsTimeIt/DungeonTools/releases

**Comment by Androzavrus** [comment]
Yeah, finally it works tnx) Just installed by your link, sr for making stupid troubles.

**Comment by travisneids** [comment]
> Yeah, finally it works tnx) Just installed by your link, sr for making stupid troubles.

No worries. We've all been there - hence my advice 😉
