### ISSUE TITLE
Slash commands and hiding minimap button lead to error

### ISSUE THREAD

**Issue by Nercus** [Tomslack/ManbabyDungeonTools#4]
By either using the Slash commands `/mdt` or `/manbabydungeontools` or going into the options to hide the minimap button leads to following error:

```lua
2x ...eManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua:1042: bad argument #1 to 'random' (interval is empty)
[string "=[C]"]: in function `random'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:1042: in function `UpdateBottomText'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:676: in function `ShowInterface'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:32: in function `OnClick'
[string "@BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:144: in function <BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals:
(*temporary) = 0
```

Edit: Clicking on the minimap button leads to same error (opens the window though)

**Comment by T3ll1nG** [comment]
The same error is also thrown when using the minimap button.

**Comment by mmpashby** [comment]
[this](https://github.com/Tomslack/ManbabyDungeonTools/pull/9) should fix the issue.

**Comment by T3ll1nG** [comment]
It didn't fix it for me.

**Comment by mmpashby** [comment]
@T3ll1nG Can you provide the error you get please? This fix did work for me on testing.

**Comment by T3ll1nG** [comment]
@Pashbee 
You suggested changing line 570 in MDT/Locales/enUS

I run Win10 en-US and the gameclient is en-US too.


I get the same error message as before. 

**If you click the minimap button:**
2x ...eManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua:1042: bad argument #1 to 'random' (interval is empty)
[string "=[C]"]: in function `random'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:1042: in function `UpdateBottomText'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:676: in function `ShowInterface'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:32: in function `OnClick'
[string "@BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:144: in function <BigWigs\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals:
(*temporary) = 0

**If you use /mdt or /manbabydungeontools after wiping saved bugs**
1x ...eManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua:1042: bad argument #1 to 'random' (interval is empty)
[string "=[C]"]: in function `random'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:1042: in function `UpdateBottomText'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:676: in function `ShowInterface'
[string "@ManbabyDungeonTools\ManbabyDungeonTools-3.3.4.lua"]:62: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5093: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4757: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4793: in function <FrameXML\ChatFrame.lua:4789>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = 0

**Comment by mmpashby** [comment]
the PR got merged but you're right it does not work because of case sensitivity on the lookup. I am sorry. I will fix and put a PR in again.

**Comment by mmpashby** [comment]
@T3ll1nG fix [here](https://github.com/Tomslack/ManbabyDungeonTools/pull/12) - I could re-produce the error you were seeing. Please let me know if that works.

**Comment by T3ll1nG** [comment]
@Pashbee that fix works just fine. 
Nice  👍

**Comment by lexaprofessional** [comment]
@Pashbee i had the same issue but your fix + changing the casing worked for me as well
