### ISSUE TITLE
Cannot install the addon

### ISSUE THREAD

**Issue by MartinZAtanasov** [Tomslack/ManbabyDungeonTools#48]
Cannot find the addon in the charachter select addon list after unziping the downloaded zip file.
Its not clear how it shoulld be installed.

**Comment by srenauld** [comment]
Hey!

One of the things I should get around to today is exactly that: writing documentation on how to manually install until we're on Curseforge properly.

Until then, you have two choices:

# Wowup

Wowup supports github repository release tracking. If you go to Get Addons, then click on the **Install from URL** button present here:
![image](https://user-images.githubusercontent.com/3967363/103273020-9063b700-49be-11eb-8e5e-b9587b0cd1df.png)

And fill in the repo like so:

![image](https://user-images.githubusercontent.com/3967363/103273041-9fe30000-49be-11eb-8a4d-92d48eebf38c.png)

Wowup will then be tracking the releases tagged on this repository, and allow you to update to the latest one, without any further manual effort. We'll stick to this release process even when the addon is on Curseforge, so it'll still work afterwards, too.

# Manual install

The old-fashioned way also works. If you go on the [**releases page**](https://github.com/LetsTimeIt/DungeonTools/releases), you can pick up the latest releases; a github trigger (action, really) packages releases whenever we tag a commit, and does a bunch of stuff behind the scenes to make it work.

Grab the versioned zip file:
![image](https://user-images.githubusercontent.com/3967363/103273144-e89ab900-49be-11eb-832e-bb71d89b18a4.png)

and extract in your `Interface/AddOns` folder. You should be getting a `DungeonTools` folder with all the files in it.

Do bear in mind that this addon and regular MDT share a global namespace object (`MDT`), and, as a result, having both installed will, for now at least, result in clashes. We'll sort that out soon-ish.

Let me know if you're still struggling, and I'll see what I can do to guide you further 🤗

**Comment by MartinZAtanasov** [comment]
I did manually installed it and it works fine.
Thank you for the good work and helping the wow community!

**Comment by srenauld** [comment]
Perfect. Glad I could help!

I'll close this issue now; if you struggle with anything else, don't hesitate to open another one (or reopen this one if it's related). Thank you for the kind words 🤗
