### ISSUE TITLE
"Drawing Line" Button Texture Missing

### ISSUE THREAD

**Issue by Nercus** [Tomslack/ManbabyDungeonTools#5]
![image](https://user-images.githubusercontent.com/48932939/103151592-a0418800-477f-11eb-9aaf-00526e3b8bb6.png)
As seen in the picture the "Drawing Line" Button in the toolbar is missing it's texture

**Comment by mmpashby** [comment]
@Nercus Thanks for reporting. I could reproduce this issue. Fixed in [PR #14](https://github.com/Tomslack/ManbabyDungeonTools/pull/14/files). 
![image](https://user-images.githubusercontent.com/3316329/103158225-7013dc80-47b3-11eb-9154-05f0512a02d3.png)
