### ISSUE TITLE
Bug: Issue with Skada?

### ISSUE THREAD

**Issue by spvi1011** [Tomslack/ManbabyDungeonTools#50]
After loading this new addon my Skada UI disappeared, can there be a conflict of some sort?

**Comment by travisneids** [comment]
Are you referring to Skada Damage Meter? Should not be causing an issue. I did test just to be sure, I can run the latest version of Skada Damager Meter and Dungeon Tools. 

Try turning off all of your addons, then reload with Skada first, then reload with Dungeon Tools and Skada only. Still having issues? Maybe try reinstalling Skada?

If you are not referring to Skada Damage Meter, I digress.

**Comment by spvi1011** [comment]
Did found the issue, was on my side. Thanks for the fast reply! 👍
