### ISSUE TITLE
have you ever considered uploading to wowinterface or curse？

### ISSUE THREAD

**Issue by Accuracyx** [Tomslack/ManbabyDungeonTools#52]
I updated the new one，so far so good

**Comment by srenauld** [comment]
It's under review at the moment :-)

**Comment by Splitix** [comment]
If you are looking for an easier install you can copy the github URL link and use wowup to install from that link.

**Comment by MrJeffer** [comment]
Hey, thank you for updating the addon! 

Is this you on Curse? https://www.curseforge.com/wow/addons/dungeon-tools before i go downloading.

Thanks again!

**Comment by rory-ferguson** [comment]
> Hey, thank you for updating the addon!
> 
> Is this you on Curse? https://www.curseforge.com/wow/addons/dungeon-tools before i go downloading.
> 
> Thanks again!

Yes it is

**Comment by srenauld** [comment]
The add-on was reviewed while I was asleep. So, yes, it is!

Hold on to your hats, though; I still need to check how to do automated releases on there (I initially banked on using github actions to prepare releases, but curse has their own builder when it comes to fetched updates. I'll likely switch it to manual and build a GH action to upload remotely). For now, though, the releases are consistent.

**Comment by layday** [comment]
You can use the BigWigs packager for this purpose - you already have a `pkgmeta` file in the repo.  You'll find a sample workflow which uploads to GH, CF and WoWI [here](https://github.com/layday/wow-addon-template/blob/main/.github/workflows/release.yaml).

**Comment by Atlanta** [comment]
You can also use [ajour](https://www.getajour.com/) and install/update add-ons from GitHub repos.


![image](https://user-images.githubusercontent.com/3481141/103369445-71eae200-4aca-11eb-84b2-1655b57f1052.png)

**Comment by erigul** [comment]
In instawow I couldn't find it searching for dungeon tools, but it shows up with a search for `curse:432055`.
Is this just because it's recently added and not discoverable yet?

**Comment by layday** [comment]
>  Is this just because it's recently added and not discoverable yet?

Yes, the catalogue is updated once daily at 00:00 UTC.

Edit: I've pushed an update to the catalogue.

**Comment by sollie** [comment]
To install with CurseBreaker:
`install gh:LetsTimeIt/DungeonTools`

![image](https://user-images.githubusercontent.com/113411/103371213-30106a80-4acf-11eb-8126-b775c2833494.png)

**Comment by Oglaf** [comment]
> LetsTimeIt/DungeonTools

I completely forgot CurseBreaker could install addons from gitHub, thx!

**Comment by srenauld** [comment]
We're now on curseforge, so this can be closed 😄
