### ISSUE TITLE
How i can insttal it?

### ISSUE THREAD

**Issue by Hexix23** [Tomslack/ManbabyDungeonTools#61]
Hey , sorry for this obviusly question, but i Put the comppressed zip on retail but the addon didnt appear on the Game.

Thanks everyone will help me 👍

**Comment by Garabound** [comment]
https://www.curseforge.com/wow/addons/dungeon-tools

from curse, off course

**Comment by Hexix23** [comment]
I mean , I install on forge and after that i install this one? Or how i can do it to restore the Data of the Mobs .D
Feeling like a noobi

**Comment by Tomslack** [comment]
Hi there, You can either just straight up install from this by download the release asset, or you can just download it from the linked curseforge page above. 

It's a seperate addon from the one without the mob data!

**Comment by Hexix23** [comment]
Im dumb, can u explain what i need to do to take the date on the game.
Sorry for sure
