### ISSUE TITLE
QOL improvements

### ISSUE THREAD

**Issue by LennoxP90** [Tomslack/ManbabyDungeonTools#69]
I would love to have the ability to hide the right side bar and only show the map in sort of a read only view mode as my main usage is leaving it up during the dungeon, also having it auto swap to the correct floor like in Theatre of Pain would be awesome.

**Comment by srenauld** [comment]
The read-only mode you're talking about is exactly #67 . It's something I will look into implementing, as it would be insanely valuable for people whenever they're trying a new route out.

The auto-swap should already be working out-of-combat. We released this with 1.1.6, or should have; subzones are accounted for in every SL dungeon and MDT should be swapping to it when opened in that dungeon. I'll check when my buddies are done raiding to make sure I'm not lying, though 😄
