### ISSUE TITLE
Updating from ManBabyDungeonTools?

### ISSUE THREAD

**Issue by DosParkers** [Tomslack/ManbabyDungeonTools#75]
How do I go from ManBaby to DungeonTools without wiping out my existing routes?

**Comment by jakubrpawlowski** [comment]
To do that you need to use url [https://github.com/Tomslack/ManbabyDungeonTools](https://github.com/Tomslack/ManbabyDungeonTools) instead [https://github.com/LetsTimeIt/DungeonTools](https://github.com/LetsTimeIt/DungeonTools). If you're using WoWUp.io go to the tab "Get Addons", click "Install from URL" and paste first link.

**Comment by madar2252** [comment]
I think you can just rename your manbabydungeontools.lua to dungeontools.lua in your WTF folder, and edit the first line within the file (change the name on the same way). At least this is what I did to keep the routes from mythicdungeontools into dungeontools. (have a backup of the old manbabydungeontools.lua, as if you mess up something, the client delete it)

**Comment by DosParkers** [comment]
Thanks @madar2252 that's the solution I was looking for. I ended up just redoing the paths as I spend a lot of time fiddling around with different paths anyways.
