### ISSUE TITLE
Halls of Atonement inspiring mistake

### ISSUE THREAD

**Issue by madar2252** [Tomslack/ManbabyDungeonTools#77]
One of the Stonefiend Anklebiter is marked for inspiring in G36, but he wasn't

**Comment by srenauld** [comment]
Just went and checked; you're right. Will correct shortly. Thank you for the report!

We never pull that group so it didn't show up on my own logs 😢

**Comment by srenauld** [comment]
Released in `v1.1.9`. Thank you for the report 👍
