### ISSUE TITLE
Global namespace polluting

### ISSUE THREAD

**Issue by Dairyman** [Tomslack/ManbabyDungeonTools#85]
`mdtDB`, `oldPresetLen`, `newPresetLen`, and `currentIdx` should be local. 

https://github.com/LetsTimeIt/DungeonTools/blob/e3b4cde1409654446a5e18147ecab8e53c1eeb34/DungeonTools.lua#L646-L655

**Comment by srenauld** [comment]
Will fix tomorrow. Sorry about that

**Comment by srenauld** [comment]
Released in 1.1.11!
