### ISSUE TITLE
Suggestion: Informations in the Nameplate or Tooltip

### ISSUE THREAD

**Issue by Rubyurek** [Tomslack/ManbabyDungeonTools#86]
Would be nice to have the function to see in the tooltip or Nameplate which Mobs i mark in Dungeon Tools.
For Example: I mark some mobs on the right side and ingame when i run the route it must show it on the tooltip that i mark them.

**Comment by CalistusK** [comment]
Refer to #40 where this is being discussed in more detail.

**Comment by Rubyurek** [comment]
ahh lol thanks^^
