### ISSUE TITLE
Selecting other dungeon is broken

### ISSUE THREAD

**Issue by itsmeAnRa** [Tomslack/ManbabyDungeonTools#91]
Hi,

I have an issue while selecting an other dungeon on the current version (1.1.12) it doesn't display the sub maps and the actual map anymore.
![image](https://user-images.githubusercontent.com/6908332/103535703-7f6ce700-4e91-11eb-80a1-896ac77434b0.png)

Occurs on Other side, Mists, Plaguefall, Sanguine Depth, Theater of pain. If logs are needed, please let me know.

**Comment by travisneids** [comment]
I can not repeat this issue on 1.1.12. Just to make sure I understand you correctly you are saying that you are unable to select a different dungeon's sub map while in another dungeon?

**Comment by srenauld** [comment]
Same issue as #83  . It's a route having a `value = 0` rather than being a proper table.

It's on my list and a pretty high prio; I'll let you know when I get it fixed.
